'use strict';

// Ursprünglicher Gin-Katalog, extrahiert aus einem Backup der alten
// index.html/ginperium.php. Wird beim ersten Start automatisch in eine
// leere gins-Tabelle geschrieben (siehe seedGinsIfEmpty in diesem Modul).

const GIN_SEED = [
    {
        name: "Bobby's",
        image: 'gins/Bobbys.jpg',
        region: 'Niederlande / Schiedam',
        taste: 'Frucht',
        alcohol: 'ALC.: 42 %',
        cost: '26,90€ || 0,7l',
        category: 'New Western Dry Gin',
        botanicals: 'Orangenschale, Hagebutte, Nelke, Koriander, Zitronengras, Zimt, Kubeben-Pfeffer',
        story: 'Bobby’s Schiedam Dry Gin ist benannt nach ”Bobby“ Alfons, geboren in Naku (Indonesien) und ausgewandert in die Niederlande. Seine Rezeptur verbindet indonesischen Geist und holländische Leidenschaft – Genever-Tradition aus dem 18. Jahrhundert fusioniert mit indonesischen Kräutermischungen.',
        perfectServe: 'Fever-Tree Indian & Orangenzeste',
    },
    {
        name: 'Star of Bombay',
        image: 'gins/Bombay.jpg',
        region: 'England / Hampshire',
        taste: 'Kräuter',
        alcohol: 'ALC.: 47,5 %',
        cost: '27,70€ || 0,7l',
        category: 'London Dry Gin',
        botanicals: 'Süßholzwurzel, Zimt, Pfeffer, Koriander, Lilie, Angelika, Mandel, Zitrone',
        story: 'Der Star of Bombay ist der Premium-Gin im Portfolio der Laverstoke Mill Distillery. Der Geschmack ist kraftvoll und vollmundig. Zunächst entfalten sich die Aromen von Wacholder und Koriander, bevor eine merkliche Schärfe von Pfeffer und Iriswurzel den Mundraum kurzzeitig einnimmt. Es folgen frische Zitrone und Bergamotte, ein Anklang von Zimt und eine Spur Angelika. Im milden Nachklang klingen die Nuancen von Wacholder und Koriander, Pfeffer, Zitrus, Angelika, etwas Lakritze sowie würzig-herbe Paradieskörner beachtlich lang nach.',
        perfectServe: 'Fever-Tree Indian & Zitrone',
    },
    {
        name: 'Citadelle',
        image: 'gins/Citadelle.jpg',
        region: 'Frankreich / Ars',
        taste: 'Frucht',
        alcohol: 'ALC.: 44 %',
        cost: '27,80€ || 0,7l',
        category: 'London Dry Gin',
        botanicals: 'Orangenzeste, Sternanis, Zimt, Süssholz, Kardamom, Kreuzkümmel, Koriander',
        story: 'Der Citadelle Gin de France ist der erste französische Craft Gin und wird seit 1996 im Château de Bonbonnet bei Ars hergestellt. Damit für den Citadelle nur die besten Beeren verwendet werden, bauen die Produzenten ihren Wacholder selbst an. Das Destillationsverfahren in kleinen Kupferkesseln (wie beim Cognac) über offener Flamme ist einzigartig und verleiht dem Gin seinen üppig-weichen Charakter.',
        perfectServe: 'Thomas Henry Tonic & Orange',
    },
    {
        name: 'Gin Mare',
        image: 'gins/Mare.jpg',
        region: 'Spanien / Barcelona',
        taste: 'Mediterran',
        alcohol: 'ALC.: 42,7 %',
        cost: '32,90 € || 0,7l',
        category: 'Distilled Gin',
        botanicals: 'Rosmarin, Basilikum, Thymian, Olive',
        story: 'Ein Gin der die mediterrane Lebenskultur in sich vereint. Rosmarin aus Griechenland, Basilikum aus Italien, Thymian aus der Türkei und Arbequina-Oliven sind hier die besonderen Zutaten des Gins. Alle Botanicals werden einzeln destilliert, geblendet und dann noch einmal destilliert, somit ist das Produktionsverfahren sehr aufwändig.',
        perfectServe: 'Fever-Tree Mediterranean & Rosmarinzweig',
    },
    {
        name: 'GIN NO. 7',
        image: 'gins/NO7.jpg',
        region: 'Deutschland / Mosbach',
        taste: 'Frucht',
        alcohol: 'ALC.: 43 %',
        cost: '39,50€ || 0,5l',
        category: 'Dry Gin',
        botanicals: 'Limette, Gurke, Piment, Zimt',
        story: 'Der "Inge & der Honigbär" Gin wird im London Dry Verfahren hergestellt und ist auf 120 Flaschen pro Charge limitiert. Gin odenwälder NO.7 fällt im ersten Moment durch Zitrusnoten am Gaumen auf. Im Hintergrund kommt langsam der Wacholder zum Vorschein und auch die milde Note von Zimt und die schöne Frische der Gurke. Piment dominiert etwas im Gaumen, allerdings holt die Gurke den doch schweren Piment wieder zurück auf den Boden.',
        perfectServe: 'Thomas Henry Tonic & Gurkenscheibe',
    },
    {
        name: 'GIN SUL',
        image: 'gins/Sul.jpg',
        region: 'Deutschland / Hamburg',
        taste: 'Frucht',
        alcohol: 'ALC.: 43 %',
        cost: '31,50 € || 0,5l',
        category: 'Dry Gin',
        botanicals: 'Koriander, Rosmarin, Piment, Lavendel, Zitrone',
        story: 'Feinste Zutaten wie das Zistrosenkraut und Zitronen von der Westalgarve verleihen diesem Hamburger Gin seit 2013 seinen portugiesischen Spirit. Bei der Produktion in Hamburg fördern bis zu 326 Meter tiefe Brunnen das Wasser aus den Sanden und Kiesen der Saale-Eiszeit hinauf. Gin Sul wird von Hand in Tonflaschen gefüllt, eine Hommage an die Ursprünge des Gins, der als Genever in Tonkrügen lagerte.',
        perfectServe: 'Thomas Henry Tonic & Zitronenzeste',
    },
    {
        name: 'Hendrick’s',
        image: 'gins/Hendricks.jpg',
        region: 'Schottland / North Lanarkshire',
        taste: 'Frucht',
        alcohol: 'ALC.: 44 %',
        cost: '29,36 € || 0,7l',
        category: 'Distilled Gin',
        botanicals: 'Rose, Gurke, Koriander, Kümmel, Kubebenpfeffer, Holunder',
        story: 'In der Apotheker Flasche präsentiert, ist dieser preisgekrönte Klassiker nach eigener Aussage "not for everyone", nicht zuletzt aufgrund der beiden Leit-Botanicals, Rosen und Gurken. Ebenfalls besonders ist, dass dieser Gin in zwei verschiedenen Kesseln gebrannt wird, wobei beide Destillate allein schon einen vorzüglichen Gin abgeben würden, danach aber vermählt werden.',
        perfectServe: 'Thomas Henry Tonic & Gurkenscheibe',
    },
    {
        name: 'Junimperium Blended',
        image: 'gins/Junimperium.jpg',
        region: 'Estland / Telliskivi',
        taste: 'Frucht',
        alcohol: 'ALC.: 45 %',
        cost: '41,90€ || 0,7l',
        category: 'Blended Dry Gin',
        botanicals: 'Koriander, Angelika, Kümmel, Thymian',
        story: 'Unser einzigartiger Geschmack setzt sich aus drei der besten Wacholderbeeren der Welt zusammen, ergänzt durch Koriander, Angelikawurzel, Kümmel, Thymian und zwei geheime Zutaten. Alle Zutaten werden separat destilliert und zu einem reichhaltigen, leicht zitrusartigen Gin mit einer leicht pfeffrigen Note und einem starken Wacholdergeschmack gemischt. Aufgrund des höheren Gehalts an Wacholderbeeren und ätherischen Ölen im Gin wird der Cocktail leicht trüb, wenn er mit Tonic und Eis gemischt wird.',
        perfectServe: 'Thomas Henry Tonic & Ingwer',
    },
    {
        name: 'Knut Hansen',
        image: 'gins/KnutHansen.jpg',
        region: 'Deutschland / Hamburg',
        taste: 'Kräuter',
        alcohol: 'ALC.: 42 %',
        cost: '29,90 € || 0,5l',
        category: 'Dry Gin',
        botanicals: 'Basilikum, Apfel, Wacholder, Gurke, Rose',
        story: 'Der Name des Gins basiert auf der Legende eines Seemanns aus Hamburg, welcher im 18. Jahrhundert die Weltmeere besegelte. Die entstandene Rezeptur umfasst 14 vielfach aus dem norddeutschen Raum stammende Botanicals, angeführt von den Schlüsselzutaten Wacholder, Basilikum, Gurke und Altländer Äpfel sowie Rosenblüten.',
        perfectServe: 'Thomas Henry Tonic & Apfel',
    },
    {
        name: 'Le Tribute',
        image: 'gins/LeTribute.jpg',
        region: 'Spanien / Vilanova',
        taste: 'Frucht',
        alcohol: 'ALC.: 43 %',
        cost: '33,88 € || 0,7l',
        category: 'Dry Gin',
        botanicals: 'Zitronengras, Orange, Zitrone, Grapefruit, Kumquat, Mandarine, Limette',
        story: 'Hergestellt wird der Gin in einer der ältesten Destillerien Spaniens, welche 1835 von der Familie Giro gegründet wurde. Le Tribute ist ein aromatischer Dry-Gin mit erfrischender, stark präsenter Zitronennote und feinen Aromen von Wacholder, die sich angenehm im Hintergrund halten. Die sieben Botanicals werden zuerst einzeln destilliert und zum Schluss harmonisch aufeinander abgestimmt. Obwohl dieser Gin einen Alkoholanteil von 43 Prozent aufweist, ist er auch pur getrunken mild.',
        perfectServe: 'Thomas Henry Tonic & Grapefruitzeste',
    },
    {
        name: 'Monkey 47',
        image: 'gins/Monkey47.jpg',
        region: 'Deutschland / Schwarzwald',
        taste: 'Kräuter',
        alcohol: 'ALC.: 47 %',
        cost: '39,99 € || 0,5l',
        category: 'Schwarzwald Dry Gin',
        botanicals: 'Brombeerblatt, Schlehe, Tannensprosse, Geißblatt, Preiselbeere',
        story: 'Basierend auf insgesamt 47 Botanicals, wie Brombeerblätter, Schlehen, Tannensprossen und Geißblatt, sind die Hauptzutat dieses Gins lokale Preiselbeeren, das ”pièce de résistance“. Monkey 47 ist nach einer alten Schwarzwälder Rezeptur hergestellt und lagert 100 Tage in Steingutfässern, bevor er mit Quellwasser auf Trinkstärke herabgesetzt wird.',
        perfectServe: 'Schweppes Dry & Grapefruitscheibe',
    },
    {
        name: 'Needle Gin',
        image: 'gins/Needle.jpg',
        region: 'Deutschland / Schwarzwald',
        taste: 'Kräuter',
        alcohol: 'ALC.: 40 %',
        cost: '19,99€ || 0,5l',
        category: 'Dry Gin',
        botanicals: 'Fichtennadeln, Lavendel, Ingwer',
        story: 'Die Einzigartigkeit des Gins liegt darin, dass er mit von Hand gepflückten Fichtennadeln der „Gemeinen Fichte“ behutsam destilliert wird. Blumiger Lavendel in Abstimmung mit der typischen Schärfe des Ingwers prägen den Geschmack. Zudem verwöhnt der Needle mit einer Zitrusnote aus sonnengereiften Zitronen und Orangen bester Qualität.',
        perfectServe: 'Thomas Henry Tonic & Orangenscheibe',
    },
    {
        name: 'Opihr Oriental Spiced',
        image: 'gins/Opihr.jpg',
        region: 'England / London',
        taste: 'Frucht',
        alcohol: 'ALC.: 42,5 %',
        cost: '31,72€ || 0,7l',
        category: 'London Dry Gin',
        botanicals: 'Ingwer, Kubebenpfeffer, Koriander, Orange, Kreuzkümmel, Grapefruit, Engelwurz, Kardamom',
        story: 'Der Oriental Spiced London Dry Gin von Opihr macht seinem Namen alle Ehre – Pfefferbeeren aus Indonesien, schwarzer, indischer Pfeffer und Kardamom aus Marokko sind nur drei der Zutaten, die diesen orientalisch gewürzten London Gin nicht nur geografisch aus der Masse emporheben. Die alt ehrwürdige, englische Gin-Brennerei G & J Distillers verwendet für diesen erlesenen Gin die Gewürze, die im 15. und im 16. Jahrhundert auf der sogenannten Gewürzstraße gehandelt wurden. Der vollmundige Ophir Oriental Gin besticht durch Wacholder- und Zitrusaromen, die von reichen, erdigen und sanft würzigen orientalischen Aromen (Kardamom, Pfeffer, Datteln, etc.) hervorragend ausbalanciert werden und für ein erfrischend kräftiges Finish sorgen.',
        perfectServe: 'Thomas Henry Tonic & Ingwer',
    },
    {
        name: 'ROKU GIN',
        image: 'gins/Roku.jpg',
        region: 'Japan / Osaka',
        taste: 'Frucht',
        alcohol: 'ALC.: 43 %',
        cost: '20,81€ || 0,7l',
        category: 'Japanese Craft Gin',
        botanicals: 'Sakura, Sencha-Tee, Gyokuro-Tee, Sansho-Pfeffer, Yuzu-Frucht',
        story: 'Das japanische Prinzip des Shun beschreibt den Moment der perfekten Reife und bezieht sich auf die Tradition, jede Speise und jedes Getränk in der richtigen Jahreszeit zu genießen, nur dann, wenn die Zutaten auf dem Höhepunkt ihres Geschmacks sind. Diesem Konzept folgend, werden die Botanicals für Roku ausschließlich im Moment ihrer optimalen Reife geerntet, wodurch das jeweilige Aroma bestmöglich extrahiert werden kann. Für Roku bedeutet das, dass sich die Ernte über ein ganzes Jahr erstreckt: im Frühling Sakura-Blüten und -blätter, im Sommer Sencha- und Gyokuro-Tee, im Herbst der Sansho-Pfeffer und im Winter die Yuzu-Frucht.',
        perfectServe: 'Thomas Henry Tonic & Ingwer',
    },
    {
        name: 'Six Dogs Honey & Lime',
        image: 'gins/SixDogs.jpg',
        region: 'Süd Afrika / Karoo',
        taste: 'Frucht',
        alcohol: 'ALC.: 43 %',
        cost: '52,90€ || 0,7l',
        category: 'Dry Gin',
        botanicals: 'Limette, Honig, Wildpflanze',
        story: 'Ein eleganter Schmelz des Honigs, dazu spritzige Aromen der Limette und ein Arrangement aus gin-typischen Gewürzen, so einfach lässt sich der vierte Gin aus dem Hause Six Dogs beschreiben. Der Honig wird auf der eigenen Farm in der Halbwüstenlandschaft Karoo hergestellt, genau wie die Limette aus eigenem Anbau. Dazu gesellen sich gin-typische Gewürze, die den Geschmack und die Aromatik wunderbar abrunden.',
        perfectServe: 'Thomas Henry Tonic & Limette',
    },
    {
        name: 'Tanqueray Imported',
        image: 'gins/TanquerayImported.jpg',
        region: 'England / London',
        taste: 'Kräuter',
        alcohol: 'ALC.: 47,3 %',
        cost: '16,90€ || 0,7l',
        category: 'London Dry Gin',
        botanicals: 'Zimt, Koriander, Angelika, Süßholz, Zitrone',
        story: 'Die Traditionsmarke wurde bereits im Jahr 1830 von Charles Tanqueray gegründet. Mit einem leicht süßlichen Anklang und den typischen Wacholderaromen verteilt sich der Tanqueray Gin im Mund. Zu den würzigen Nuancen der Koriandersamen gesellen sich die frischen Noten der verwendeten Zitrusfrüchte. Abgerundet wird der Geschmack letztendlich von einem dezenten Anklang der Lakritze und einem Hauch Zimt.',
        perfectServe: 'Fever-Tree Indian Tonic & Zitrone',
    },
    {
        name: 'Tanqueray Flor de Sevilla',
        image: 'gins/TanqueraySevilla.jpg',
        region: 'England / London',
        taste: 'Frucht',
        alcohol: 'ALC.: 41,3 %',
        cost: '17,67€ || 0,7l',
        category: 'London Dry Gin',
        botanicals: 'Zimt, Koriander, Angelika, Süßholz, Orangen',
        story: 'Für den Flor de Sevilla griff man auf ein altes Rezept von Charles Tanqueray zurück. Flor de Sevilla bedeutet übersetzt so viel wie die Blüte von Sevilla. Die Basis des Gins ist der klassische London Dry Gin, welcher durch sonnengereifte Orangen und Orangenblüten aus Sevilla verfeinert wird. Man schmeckt eine angenehme Honigsüße, sowie suggestive bittersüße Noten der Sevilla Orangen und dezente Nuancen vom Wacholder und Kräutern im Hintergrund.',
        perfectServe: 'Fever-Tree Mediterranean & Orangenzeste',
    },
    {
        name: 'The Illusionist',
        image: 'gins/Illusionist.jpg',
        region: 'Deutschland / München',
        taste: 'Frucht',
        alcohol: 'ALC.: 45 %',
        cost: '31,92 € || 0,5l',
        category: 'Dry Gin',
        botanicals: 'Süßholz, Rosmarin, Kardamom, Zitrone',
        story: 'Der Illusionist Dry Gin in Bio-Qualität wird in einer klassischen Pot Still destilliert und von Hand, ungefiltert in Steingutflaschen abgefüllt. Das Besondere ist seine tiefblaue Farbe, die durch Infusion mit einer Blüte aus Fernost entsteht. Der natürliche Farbstoff dieser Blüte reagiert mit Säure, wie z. B. Tonic Water. Er verändert seine Farbe und verwandelt sich als Gin & Tonic vom Blauen in ein sanftes Rosa.',
        perfectServe: 'Thomas Henry Tonic & Rosmarinzweig',
    },
    {
        name: 'Ursel Dark Forest',
        image: 'gins/Ursel.jpg',
        region: 'Deutschland / Oberursel',
        taste: 'Kräuter',
        alcohol: 'ALC.: 47 %',
        cost: '39,95 € || 0,5l',
        category: 'London Dry Gin',
        botanicals: 'Melisse, Eberesche, Rosmarin, Lavendel, Ingwer, Koriander, Zitrone',
        story: 'Geschmacklich präsentiert sich der Dark Forest kraftvoll aber dennoch mild. Vordergründig schmeckt man waldige und ätherische Noten der jungen Fichtentriebe. Hinzu gesellen sich frische Aromen der Zitrusfrüchte, sowie Noten von Kräutern und florale Komponenten. Gebrannt wird der Gin in einer kleinen Manufaktur in Oberursel und jede Flasche wird von Hand abgefüllt. Für den vollen Geschmack wird auf die Filtration des Gins verzichtet.',
        perfectServe: 'Fever-Tree Indian Tonic & Orangenzesten',
    },
];

/**
 * Schreibt den Ausgangs-Katalog in die gins-Tabelle, aber nur solange sie
 * leer ist. Damit wird eine frische Datenbank (z.B. ein neues Docker-
 * Volume auf dem Pi) automatisch mit dem ursprünglichen Katalog befüllt,
 * ohne bereits vom Admin gepflegte Daten zu überschreiben.
 */
function seedGinsIfEmpty(repo) {
    if (repo.listGins().length > 0) {
        return 0;
    }

    const { newId } = require('../lib/ids');
    const { nowIso } = require('../lib/time');

    for (const gin of GIN_SEED) {
        const timestamp = nowIso();
        repo.createGin({ id: newId(), ...gin, createdAt: timestamp, updatedAt: timestamp });
    }

    return GIN_SEED.length;
}

module.exports = { GIN_SEED, seedGinsIfEmpty };
